### ISSUE TITLE
Cant get past peer dependency

### ISSUE THREAD

**Issue by martym00se** [qlik-oss/sn-pivot-table#299]
Thinking the peer dependency @qlik-trial/sprout@">=2.51.0 should be a devdependency - currently version 2.0 cannot be installed by the public because of this.

ERESOLVE overriding peer dependency
npm WARN While resolving: @nebula.js/sn-pivot-table@2.0.0
npm WARN Found: @qlik-trial/sprout@undefined
npm WARN node_modules/@qlik-trial/sprout
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @qlik-trial/sprout@">=2.51.0" from @nebula.js/sn-pivot-table@2.0.0
npm WARN node_modules/@nebula.js/sn-pivot-table
npm WARN   @nebula.js/sn-pivot-table@"*" from the root project
npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.7.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.7.1
npm notice Run npm install -g npm@9.7.1 to update!
npm notice 
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@qlik-trial%2fsprout - Not found
npm ERR! 404 
npm ERR! 404  '@qlik-trial/sprout@>=2.51.0' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by SBylemans** [comment]
+1 having the same issue

**Comment by zangerls** [comment]
Has anyone found a solution for this yet?

Judging from the weekly npm downloads I'd have figured installing `v2.0.0` would work but I still get the above mentioned error. 

Also, it seems as though `v1.x.x` might still work but would require me to downgrade from `@nebula.js/stardust@4.x.x` to `v3.x.x` which is also really not what I had planned.

Surely this package hasn't been "unusable" since June 19th?

Thanks in advance!

**Comment by cbt1** [comment]
Looking into this 👀
